[project]
name = "pso-bot"
version = "0.1.0"
description = "PSO discord bot using LLM core"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.0",
    "beautifulsoup4>=4.14.3",
    "discord-py>=2.7.1",
    "google-genai>=1.68.0",
    "groq>=1.1.1",
    "html5lib>=1.1",
    "lxml>=6.0.2",
    "markdownify>=1.2.2",
    "motor>=3.7.1",
    "prometheus-client>=0.24.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pylint>=4.0.5",
]
